services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "20"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    container_name: kapitmas_whatsapp_go
    image: gedeadisurya/go-whatsapp-multi:kapitmas-v3
    restart: "on-failure"
    ports:
      - "${PORT:-3003}:${PORT:-3003}"
    networks:
      - go_kapitmas
    env_file:
      - src/.env
    volumes:
      - ./whatsapp_data:/app/storages
networks:
  go_kapitmas:
    driver: bridge
